namespace FftaExtract.Providers
{
    using System.Collections.Generic;

    public class CompetitionCategoryMapping
    {
        public static Dictionary<string, int> code = new Dictionary<string, int>()
                                                         {
                                                             { "2009_Salle_SH_CL", 3393 },
                                                             { "2009_Salle_SF_CL", 3394 },
                                                             { "2012_Salle_JH_CL", 5458 },

                                                             { "2013_Salle_CF_BB", 6143},
                                                             { "2013_Salle_CH_BB", 6144},
                                                             { "2013_Salle_SCF_BB", 6111},
                                                             { "2013_Salle_SCH_BB", 6110},
                                                             { "2013_Salle_BF_CL", 6112},
                                                             { "2013_Salle_BH_CL", 6113},
                                                             { "2013_Salle_MF_CL", 6114},
                                                             { "2013_Salle_MH_CL", 6115},
                                                             { "2013_Salle_CF_CL", 6116},
                                                             { "2013_Salle_CH_CL", 6117},
                                                             { "2013_Salle_JF_CL", 6118},
                                                             { "2013_Salle_JH_CL", 6119},
                                                             { "2013_Salle_SF_CL", 6120},
                                                             { "2013_Salle_SH_CL", 6121},
                                                             { "2013_Salle_VF_CL", 6122},
                                                             { "2013_Salle_VH_CL", 6123},
                                                             { "2013_Salle_SVF_CL", 6124},
                                                             { "2013_Salle_SVH_CL", 6125},
                                                             { "2013_Salle_CF_CO", 6141},
                                                             { "2013_Salle_CH_CO", 6142},
                                                             { "2013_Salle_JF_CO", 6126},
                                                             { "2013_Salle_JH_CO", 6127},
                                                             { "2013_Salle_SF_CO", 6128},
                                                             { "2013_Salle_SH_CO", 6129},
                                                             { "2013_Salle_VF_CO", 6130},
                                                             { "2013_Salle_VH_CO", 6131},
                                                             { "2013_Salle_SVF_CO", 6132},
                                                             { "2013_Salle_SVH_CO", 6133},

                                                             { "2013_Fita_BF_CL", 6600},
                                                             { "2013_Fita_BH_CL", 6601},
                                                             { "2013_Fita_MF_CL", 6602},
                                                             { "2013_Fita_MH_CL", 6603},
                                                             { "2013_Fita_CF_CL", 6604},
                                                             { "2013_Fita_CH_CL", 6605},
                                                             { "2013_Fita_JF_CL", 6606},
                                                             { "2013_Fita_JH_CL", 6607},
                                                             { "2013_Fita_VF_CL", 6610},
                                                             { "2013_Fita_VH_CL", 6611},
                                                             { "2013_Fita_SVF_CL", 6612},
                                                             { "2013_Fita_SVH_CL", 6613},
                                                             { "2013_Fita_SCF_CL", 6716},
                                                             { "2013_Fita_SCH_CL", 6717},
                                                             { "2013_Fita_CF_CO", 6625},
                                                             { "2013_Fita_CH_CO", 6622},
                                                             { "2013_Fita_JF_CO", 6614},
                                                             { "2013_Fita_JH_CO", 6615},
                                                             { "2013_Fita_VF_CO", 6618},
                                                             { "2013_Fita_VH_CO", 6619},
                                                             { "2013_Fita_SVF_CO", 6620},
                                                             { "2013_Fita_SVH_CO", 6621},
                                                             { "2013_Fita_SCF_CO", 6718},
                                                             { "2013_Fita_SCH_CO", 6719},

                                                             { "2014_Salle_CH_BB", 6825 },
                                                             { "2014_Salle_CF_BB", 6824 },
                                                             { "2014_Salle_SCF_BB", 6792 },
                                                             { "2014_Salle_SCH_BB", 6791 },
                                                             { "2014_Salle_BF_CL", 6793 },
                                                             { "2014_Salle_BH_CL", 6794 },
                                                             { "2014_Salle_MF_CL", 6795 },
                                                             { "2014_Salle_MH_CL", 6796 },
                                                             { "2014_Salle_CF_CL", 6797 },
                                                             { "2014_Salle_CH_CL", 6798 },
                                                             { "2014_Salle_JF_CL", 6799 },
                                                             { "2014_Salle_JH_CL", 6800 },
                                                             { "2014_Salle_SF_CL", 6801 },
                                                             { "2014_Salle_SH_CL", 6802 },
                                                             { "2014_Salle_VF_CL", 6803 },
                                                             { "2014_Salle_VH_CL", 6804 },
                                                             { "2014_Salle_SVF_CL", 6805 },
                                                             { "2014_Salle_SVH_CL", 6806 },
                                                             { "2014_Salle_CF_CO", 6822 },
                                                             { "2014_Salle_CH_CO", 6823 },
                                                             { "2014_Salle_JF_CO", 6807 },
                                                             { "2014_Salle_JH_CO", 6808 },
                                                             { "2014_Salle_SF_CO", 6809 },
                                                             { "2014_Salle_SH_CO", 6810 },
                                                             { "2014_Salle_VF_CO", 6811 },
                                                             { "2014_Salle_VH_CO", 6812 },
                                                             { "2014_Salle_SVF_CO", 6813 },
                                                             { "2014_Salle_SVH_CO", 6814 },
                                                             { "2014_Fita_BF_CL", 7250 },
                                                             { "2014_Fita_BH_CL", 7251 },
                                                             { "2014_Fita_MF_CL", 7252 },
                                                             { "2014_Fita_MH_CL", 7253 },
                                                             { "2014_Fita_CF_CL", 7254 },
                                                             { "2014_Fita_CH_CL", 7255 },
                                                             { "2014_Fita_JF_CL", 7256 },
                                                             { "2014_Fita_JH_CL", 7257 },
                                                             { "2014_Fita_VF_CL", 7260 },
                                                             { "2014_Fita_VH_CL", 7261 },
                                                             { "2014_Fita_SVF_CL", 7262 },
                                                             { "2014_Fita_SVH_CL", 7263 },
                                                             { "2014_Fita_SCF_CL", 7360 },
                                                             { "2014_Fita_SCH_CL", 7361 },
                                                             { "2014_Fita_CF_CO", 7275 },
                                                             { "2014_Fita_CH_CO", 7272 },
                                                             { "2014_Fita_JF_CO", 7264 },
                                                             { "2014_Fita_JH_CO", 7265 },
                                                             { "2014_Fita_VF_CO", 7268 },
                                                             { "2014_Fita_VH_CO", 7269 },
                                                             { "2014_Fita_SVF_CO", 7270 },
                                                             { "2014_Fita_SVH_CO", 7271 },
                                                             { "2014_Fita_SCF_CO", 7362 },
                                                             { "2014_Fita_SCH_CO", 7363 },
                                                              
                                                             { "2015_Salle_CF_BB", 8700},
                                                             { "2015_Salle_CH_BB", 8701},
                                                             { "2015_Salle_SCF_BB", 8668},
                                                             { "2015_Salle_SCH_BB", 8667},
                                                             { "2015_Salle_BF_CL", 8669},
                                                             { "2015_Salle_BH_CL", 8670},
                                                             { "2015_Salle_MF_CL", 8671},
                                                             { "2015_Salle_MH_CL", 8672},
                                                             { "2015_Salle_CF_CL", 8673},
                                                             { "2015_Salle_CH_CL", 8674},
                                                             { "2015_Salle_JF_CL", 8675},
                                                             { "2015_Salle_JH_CL", 8676},
                                                             { "2015_Salle_SF_CL", 8677},
                                                             { "2015_Salle_SH_CL", 8678},
                                                             { "2015_Salle_VF_CL", 8679},
                                                             { "2015_Salle_VH_CL", 8680},
                                                             { "2015_Salle_SVF_CL", 8681},
                                                             { "2015_Salle_SVH_CL", 8682},
                                                             { "2015_Salle_CF_CO", 8698},
                                                             { "2015_Salle_CH_CO", 8699},
                                                             { "2015_Salle_JF_CO", 8683},
                                                             { "2015_Salle_JH_CO", 8684},
                                                             { "2015_Salle_SF_CO", 8685},
                                                             { "2015_Salle_SH_CO", 8686},
                                                             { "2015_Salle_VF_CO", 8687},
                                                             { "2015_Salle_VH_CO", 8688},
                                                             { "2015_Salle_SVF_CO", 8689},
                                                             { "2015_Salle_SVH_CO", 8690},

                                                             { "2015_Fita_BF_CL", 9149},
                                                             { "2015_Fita_BH_CL", 9150},
                                                             { "2015_Fita_MF_CL", 9151},
                                                             { "2015_Fita_MH_CL", 9152},
                                                             { "2015_Fita_CF_CL", 9153},
                                                             { "2015_Fita_CH_CL", 9154},
                                                             { "2015_Fita_JF_CL", 9155},
                                                             { "2015_Fita_JH_CL", 9156},
                                                             { "2015_Fita_VF_CL", 9159},
                                                             { "2015_Fita_VH_CL", 9160},
                                                             { "2015_Fita_SVF_CL", 9161},
                                                             { "2015_Fita_SVH_CL", 9162},
                                                             { "2015_Fita_SCF_CL", 9259},
                                                             { "2015_Fita_SCH_CL", 9260},
                                                             { "2015_Fita_CF_CO", 9174},
                                                             { "2015_Fita_CH_CO", 9171},
                                                             { "2015_Fita_JF_CO", 9163},
                                                             { "2015_Fita_JH_CO", 9164},
                                                             { "2015_Fita_VF_CO", 9167},
                                                             { "2015_Fita_VH_CO", 9168},
                                                             { "2015_Fita_SVF_CO", 9169},
                                                             { "2015_Fita_SVH_CO", 9170},
                                                             { "2015_Fita_SCF_CO", 9261},
                                                             { "2015_Fita_SCH_CO", 9262},
                                   

                                                         };

        public static string[] ignoredCategories = new[]
                                                        {
                                                            "2013_Fita_SH_CL",
                                                            "2013_Fita_SF_CL",
                                                            "2013_Fita_SH_CO",
                                                            "2013_Fita_SF_CO",
                                                            "2013_Salle_SCH_CL",
                                                            "2013_Salle_SCF_CL",
                                                            "2013_Salle_SCH_CO",
                                                            "2013_Salle_SCF_CO",
                                                            "2014_Fita_SH_CL",
                                                            "2014_Fita_SF_CL",
                                                            "2014_Fita_SH_CO",
                                                            "2014_Fita_SF_CO",
                                                            "2014_Salle_SCH_CL",
                                                            "2014_Salle_SCF_CL",
                                                            "2014_Salle_SCH_CO",
                                                            "2014_Salle_SCF_CO",
                                                            "2015_Salle_SCH_CL",
                                                            "2015_Salle_SCF_CL",
                                                            "2015_Salle_SCH_CO",
                                                            "2015_Salle_SCF_CO",
                                                            "2015_Fita_SH_CL",
                                                            "2015_Fita_SF_CL",
                                                            "2015_Fita_SH_CO",
                                                            "2015_Fita_SF_CO",
                                                        };
    }
}